### ISSUE TITLE
First splitfile always corrupt 

### ISSUE THREAD

**Issue by Madd33n** [naveednajam/Little-Snitch---Rule-Groups#3] opened 2018-12-31 15:03 UTC
Hi, thanks for your script. 
Sadly there seems to be a little bug in the first splitted file "stevenblack0.lsrules".
When importing this rule to the subscription, LittleSnitch pops up with an error.

I'm using LS at german language, so I just made a simple translation of the error. 

**_"The file could not be opened due to a wrong format"_**
I provided the screenshot and the corrupt file as well. 

All other splitted files (stevenblack1 to stevenblack7) dont have this problem. Import works flawlessly. 
Can you please review the output and provide a bug fix?

Thanks. 
![bildschirmfoto 2018-12-31 um 16 02 00](https://user-images.githubusercontent.com/46282808/50562597-6a46a600-0d15-11e9-9c9c-156d03674377.png)
[stevenblack0.lsrules.zip](https://github.com/naveednajam/Little-Snitch---Rule-Groups/files/2718489/stevenblack0.lsrules.zip)

**Comment by naveednajam** [comment] 2018-12-31 18:36
Hi Madd33n, thanks for highlighting this issue, Format issue is caused by inline comment tags in steventblack hostfile. I updated the script to handle inline comment for domains and uploaded new rulesets. Can you try again to import first rule and feedback the result.Thanks

**Comment by Madd33n** [comment] 2019-01-01 07:46
Hi, 

thanks for the quick fix. Now, the first splitted file can be imported without any problem. 

I also have a little request after using your script - maybe you can help :) 
I want to describe it in the "pull request" section, but i cant open a request.

So I'll describe it at another topic within the issues section. 

Have a nice day.

**Comment by naveednajam** [comment] 2019-01-01 07:51
Thanks for confirmation.I will close this issue now.

**Closed as completed by naveednajam** 2019-01-01 07:51 UTC
Labels: bug
